### PR TITLE
WIP: MEG example

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR is a fork of https://github.com/ja-che/hidimstat/pull/24

Let's first try to fix GitHub Actions.

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
@ja-che can you allow running the CIs?

**Comment by ja-che** [comment]
Sûre

**Comment by GuillaumeFavelier** [comment]
Thanks!

**Comment by GuillaumeFavelier** [comment]
Mayb we need `xvfb`, waiting for the result of the last run:

https://github.com/ja-che/hidimstat/pull/25/checks?check_run_id=2913208917#step:4:975

**Comment by GuillaumeFavelier** [comment]
But locally, it works for me too :+1: 

image

**Comment by GuillaumeFavelier** [comment]
**TL;DR:** I reproduced https://github.com/mne-tools/mne-nirs/pull/297 so I'll switch to `circle`

<details>

I added some required dependencies and configured the CIs for basic `sphinx` usage and it should be reviewed.

In the end, I think the `ammaraskar/sphinx-action@master` action does not seem compatible with `xvfb` or I did not manage to configure it properly.

The artefacts are available:

https://github.com/ja-che/hidimstat/suites/3085413492/artifacts/70429606

</details>

**Comment by GuillaumeFavelier** [comment]
Apparently the plot hangs on Circle, any idea?

**Comment by GuillaumeFavelier** [comment]
@ja-che 

We were so close!

Looks at this atefact:

https://8-259908992-gh.circle-artifacts.com/0/dev/auto_examples/plot_meg_data_example.html#sphx-glr-auto-examples-plot-meg-data-example-py

**Comment by GuillaumeFavelier** [comment]
It has been more than 20 minutes now so I think the plots are definitely hanging for some reason. Why only on CircleCI? I can't explain it.

I'll push another commit to remove CircleCI YAML configuration file so it can be disabled for the project if you don't need it.

@ja-che, you can link https://github.com/mne-tools/mne-nirs/pull/297 to follow the progress on "MNE/PyVista figures on Sphinx/GithubActions". I intend to go back on it at some point to solve this mysterious issue.

**Comment by GuillaumeFavelier** [comment]
@ja-che ready to go when CIs return happy :+1: 

Feel free to disable CircleCI on the project now.

**Comment by agramfort** [comment]
can you share a link to the artifact when you have one?

>

**Comment by GuillaumeFavelier** [comment]
They're available:

https://github.com/ja-che/hidimstat/suites/3100958266/artifacts/70883554

**Comment by agramfort** [comment]
plot_meg_data_example.html does not show a brain

>

**Comment by GuillaumeFavelier** [comment]
@agramfort , for short, the brain is showed on circle but the other examples do not work. on github actions everything is showed except the brain

**Pull request merged**
